spring:
  config:
    import: "optional:file:./application-secrets.properties"
  application:
    name: recruitment-ai-service
  profiles:
    active: dev

logging:
  level:
    com.recruitment.ai: debug
